# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ece3f38f235e1365f39e9864313ce35317c27343a5aa9004353efa3f591404d5f5233c1f2c7e50683f155752b86887bf06cac5898a8624be9cec621fbe1a0044

test:
  secret_key_base: 7af175b93fe925be1970ba5f2d033e3fee6d8b6646a6873ab320d46e0f536f0f557d816fe8c8c1a8a2e7bc9fd0b3283c381b188d5b214f3f79ea3775171d6fdd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
